### ISSUE TITLE
Issues with specter

### ISSUE THREAD

**Issue by neuromantik33** [borkdude/sci#370]
version: 0.1.1-alpha.6
platform: JVM

I'm attempting to implement a generic clojure executor processor for Apache Nifi using sci, but I'm have some issues trying to integrate [specter](https://github.com/redplanetlabs/specter). Specifically, I'm unable to execute the `path` fn due to some weird unbound var magic going on under the hood.

For instance I'm executing this code:
```clojure
(sci/eval-string "
(require '[com.rpl.specter :refer :all])
(def data {:a [{:aa 1 :bb 2} {:cc 3}] :b [{:dd 4}]})
(transform [MAP-VALS ALL MAP-VALS even?] inc data)"
    {:namespaces {'com.rpl.specter (ns-publics 'com.rpl.specter)
                  'com.rpl.specter.impl (ns-publics 'com.rpl.specter.impl)}})

=> Execution error (ExceptionInfo) at sci.impl.utils/throw-error-with-location (utils.cljc:54).
Could not resolve symbol: pathcache2320 [at line , column ]
clojure.lang.ExceptionInfo: Could not resolve symbol: pathcache2320 [at line , column ] {:type :sci/error, :line nil, :column nil}
	at sci.impl.utils$throw_error_with_location.invokeStatic(utils.cljc:54)
	at sci.impl.utils$throw_error_with_location.invoke(utils.cljc:44)
	at sci.impl.utils$throw_error_with_location.invokeStatic(utils.cljc:45)
	at sci.impl.utils$throw_error_with_location.invoke(utils.cljc:44)
	at sci.impl.analyzer$resolve_symbol.invokeStatic(analyzer.cljc:137)
	at sci.impl.analyzer$resolve_symbol.invoke(analyzer.cljc:115)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:731)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$analyze_children$fn__7633.invoke(analyzer.cljc:146)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at sci.impl.analyzer$analyze_children.invokeStatic(analyzer.cljc:146)
	at sci.impl.analyzer$analyze_children.invoke(analyzer.cljc:145)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:721)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$analyze_children$fn__7633.invoke(analyzer.cljc:146)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8154.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8154.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at sci.impl.analyzer$analyze_children.invokeStatic(analyzer.cljc:146)
	at sci.impl.analyzer$analyze_children.invoke(analyzer.cljc:145)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:668)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$expand_try.invokeStatic(analyzer.cljc:444)
	at sci.impl.analyzer$expand_try.invoke(analyzer.cljc:423)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:691)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$expand_let_STAR_$fn__7673.invoke(analyzer.cljc:255)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at sci.impl.analyzer$expand_let_STAR_.invokeStatic(analyzer.cljc:253)
	at sci.impl.analyzer$expand_let_STAR_.invoke(analyzer.cljc:250)
	at sci.impl.analyzer$expand_let.invokeStatic(analyzer.cljc:266)
	at sci.impl.analyzer$expand_let.invoke(analyzer.cljc:262)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:669)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:719)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$analyze_children$fn__7633.invoke(analyzer.cljc:146)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at sci.impl.analyzer$analyze_children.invokeStatic(analyzer.cljc:146)
	at sci.impl.analyzer$analyze_children.invoke(analyzer.cljc:145)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:721)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.analyzer$analyze_call.invokeStatic(analyzer.cljc:719)
	at sci.impl.analyzer$analyze_call.invoke(analyzer.cljc:637)
	at sci.impl.analyzer$analyze.invokeStatic(analyzer.cljc:748)
	at sci.impl.analyzer$analyze.invoke(analyzer.cljc:727)
	at sci.impl.interpreter$eval_form.invokeStatic(interpreter.cljc:647)
	at sci.impl.interpreter$eval_form.invoke(interpreter.cljc:639)
	at sci.impl.interpreter$eval_string_STAR_.invokeStatic(interpreter.cljc:659)
	at sci.impl.interpreter$eval_string_STAR_.invoke(interpreter.cljc:653)
	at sci.impl.interpreter$eval_string.invokeStatic(interpreter.cljc:668)
	at sci.impl.interpreter$eval_string.invoke(interpreter.cljc:664)
	at sci.core$eval_string.invokeStatic(core.cljc:179)
	at sci.core$eval_string.invoke(core.cljc:142)
	at user$eval2318.invokeStatic(user.clj:16)
	at user$eval2318.invoke(user.clj:16)
	...
```

I've expanded the macros regarding `transform` and `path` for informational purposes (but I will admit I'm a bit lost as to what nathan is trying to do here)
```clojure
(macroexpand '(transform [MAP-VALS ALL MAP-VALS even?] inc data))
=> (com.rpl.specter.impl/compiled-transform* (com.rpl.specter/path [MAP-VALS ALL MAP-VALS even?]) inc data)

(macroexpand '(path [MAP-VALS ALL MAP-VALS even?]))
=>
(let*
 [info__2677__auto__
  (try
   (com.rpl.specter.impl/get-cell pathcache2333)
   (catch
    java.lang.ClassCastException
    e__2675__auto__
    (if
     (clojure.core/bound? (var pathcache2333))
     (com.rpl.specter.impl/get-cell pathcache2333)
     (do
      (clojure.core/alter-var-root
       (var pathcache2333)
       (clojure.core/fn [___2676__auto__] (com.rpl.specter.impl/mutable-cell)))
      nil))))
  info__2677__auto__
  (if
   (clojure.core/nil? info__2677__auto__)
   (clojure.core/let
    [info2334
     (com.rpl.specter.impl/magic-precompilation
      [[(com.rpl.specter.impl/->VarUse MAP-VALS (var MAP-VALS) (quote MAP-VALS))
        (com.rpl.specter.impl/->VarUse ALL (var ALL) (quote ALL))
        (com.rpl.specter.impl/->VarUse MAP-VALS (var MAP-VALS) (quote MAP-VALS))
        (com.rpl.specter.impl/->VarUse even? (var even?) (quote even?))]]
      "user"
      (quote [])
      (quote [[MAP-VALS ALL MAP-VALS even?] MAP-VALS ALL MAP-VALS even?]))]
    (com.rpl.specter.impl/set-cell! pathcache2333 info2334)
    info2334)
   info__2677__auto__)
  precompiled2335
  (com.rpl.specter.impl/cached-path-info-precompiled info__2677__auto__)
  dynamic?__2678__auto__
  (com.rpl.specter.impl/cached-path-info-dynamic? info__2677__auto__)]
 (if dynamic?__2678__auto__ (precompiled2335) precompiled2335))
```
I guess the general question is can `sci` handle unbound values which seem to be the case here and honor the try/catch clause used by specter to actually define the variable late in the game.

Thanks for any insight, I would hate to go back to using `load-string` :sweat_smile:

**Comment by borkdude** [comment]
Hi! You may be able to read this conversation that happened in the sci Clojurians slack channel a while ago:

https://clojurians.zulipchat.com/#narrow/stream/180378-slack-archive/topic/sci/near/202397937

Also I took a stab at this myself and came up with this config:

https://gist.github.com/borkdude/f6abcb0ff4183df559345503cb9c621c

It's not working correctly yet. 

The issues are that specter uses macros and these macros currently have side effects in clojure.lang.RT. These side effects should be translated to side effects in the sci ctx.

**Comment by neuromantik33** [comment]
Thanks for the feedback. It’s unfortunate that such a neat little library has to perform these tricks instead of just using core.memoize , I guess Nathan didn’t want any unnecessary dependencies 😅

**Comment by borkdude** [comment]
@neuromantik33 I now got a working configuration for specter in sci:

https://gist.github.com/borkdude/f6abcb0ff4183df559345503cb9c621c

There is one caveat if you want to compile with native image, specter is using eval:

https://github.com/redplanetlabs/specter/blob/d0d6fdf5818c6b3d939c4f9dfc670e79b3563f3d/src/clj/com/rpl/specter/impl.cljc#L611

**Comment by borkdude** [comment]
OK, fully solved now:

https://github.com/borkdude/specter-sci
